# Example configuration.yaml entry
sensor:
  - platform:  wnsm
    username:  !secret vsm_username
    password:  !secret vsm_password
    device_id: !secret vsm_zaehlpunkt_1
  - platform: wnsm
    username: !secret vsm_username
    password: !secret vsm_password
    device_id: !secret vsm_zaehlpunkt_2
  - platform: wnsm
    username: !secret vsm_username
    password: !secret vsm_password
    device_id: !secret vsm_zaehlpunkt_3
