name-template: v$NEXT_MINOR_VERSION
tag-template: v$NEXT_MINOR_VERSION
categories:
  - title: ⬆️Dependencies
    label: dependencies
  - title: 🚀 Features
    labels:
    - 'feature'
    - 'enhancement'
  - title: 🐛 Bug Fixes
    labels:
      - 'patch'
      - 'fix'
      - 'bug'
      - 'bugfix'
  - title: 🧰 Maintenance
    label: chore
    
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'dependencies'
      - 'chore'
      - 'bug'
      - 'fix'
      - 'bugfix'
  default: patch
  
template: |
  ## Changes
  $CHANGES