name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Set version number"
        run: |
          python3 ${{ github.workspace }}/manage/update_manifest.py --version ${{ steps.version.outputs.version }}
      # Pack the wnsm dir as a zip and upload to the release
      - name: ZIP wnsm Dir
        run: |
          cd ${{ github.workspace }}/custom_components/wnsm
          zip wnsm.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/wnsm/wnsm.zip
          asset_name: wnsm.zip
          tag: ${{ github.ref }}
          overwrite: true